# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: CI

# Trigger this workflow whenever new code is pushed to the "main" branch or a pull request is made on the "main" branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
    
jobs:
  # This workflow contains a single job called "build". If multiple jobs were defined, they could be run parallely 
  # using two Runners. 
  build:
    # The type of runner that the job will run on. Runner is a machine that can connect to GitHub, run the steps
    # and log the results back to GitHub
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job - they cannot run in parallel.
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."    
      
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      # Runs a set of commands using the runners shell
      - name: Step 2 - List files in the repository
        run: |
          echo What is this directory?
          ls ${{ github.workspace }}
          echo
          echo Is Java installed?
          java --version
          echo
          echo Is git installed?
          git --version
          echo
          echo Is Maven installed?
          mvn --version

      # Setup Java 17 so that repository code can be compiled 
      - name: Step 3 - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: central
      
      # Compile the Java code using Maven 
      - name: Build with Maven
        run: mvn -B package --file pom.xml
